#!/bin/bash

set -euo pipefail

# Run the nestjs server in the background.
npm run start:debug >> /dev/null &

# # Give the server enough time to be ready before accepting requests.
# # Dev server startup is slow!!!

while true
c=1
do
    # Run the healthcheck.
    if [[ $(curl -I http://localhost:3000/health-check 2>&1) =~ "200 OK" ]]; then
    echo "Health check passed!"
    fi
    exit 0
    ((c++)) && ((c==20)) && break
    curl -I http://localhost:3000/health-check
    sleep 1
done

echo "Health check failed!"
exit 1
