#!/bin/bash

set -euo pipefail

# Run the nestjs server in the background.
nohup npm run start:dev >> /dev/null &

# Give the server enough time to be ready before accepting requests.
sleep 5

# Run the healthcheck.
if [[ $(curl -I http://localhost:3000/health-check 2>&1) =~ "200 OK" ]]; then
   echo "Health check passed!"
   exit 0
else
   echo "Health check failed!"
   exit 1
fi

# Cleanup.
