#!/bin/bash

# Inspired by Github's 'scripts to rule them all'.
# https://github.com/github/scripts-to-rule-them-all

set -euo pipefail

# Start uvicorn server in the background.
nohup uvicorn app.main:fast_api --port 5000 --reload > /dev/null &

# Call healthcheck.
if [[ $(httpx -m GET http://localhost:5000/health_check) =~ "Ok" ]]; then
   echo "Health check passed!"
else
    echo "Health check failed!"
    exit 1
fi
