#!/bin/bash

set -euo pipefail

# Run the uvicorn server in the background.

nohup uvicorn app.main:fast_api --port 5000 --reload >> /dev/null &

# Give the server enough time to be ready before accepting requests.
sleep 2

# Run the healthcheck.
if [[ $(httpx -m GET http://localhost:5000/health_check 2>&1) =~ "200 OK" ]]; then
   echo "Health check passed!"
   exit 0
else
   echo "Health check failed!"
   exit 1
fi

# Cleanup.
pkill -9 -ecfi python
